:icons: font
:version: 0.1.0
= AsciidoctorJ Office Extension

image:https://github.com/uniqueck/asciidoctorj-office-extension/actions/workflows/ci.yaml/badge.svg?branch=master["GitHub Actions", link="https://github.com/uniqueck/asciidoctorj-office-extension/actions/workflows/ci.yaml?branch=master"]
image:https://img.shields.io/badge/License-MIT-yellow.svg["MIT License", link="https://opensource.org/licenses/MIT"]
image:https://maven-badges.herokuapp.com/maven-central/de.uniqueck.asciidoctorj.extensions/asciidoctorj-office-extension/badge.svg?style=plastic[link="https://maven-badges.herokuapp.com/maven-central/de.uniqueck.asciidoctorj.extensions/asciidoctorj-office-extension"]

This AsciidoctorJ extension helps you to use office documents in your asciidoc toolchain.

== Installation

To use this extension declare it as a dependency in asciidoctor-maven-plugin configuration.

[subs="attributes, verbatim"]
[source, xml]
----
<plugin>
	<groupId>org.asciidoctor</groupId>
	<artifactId>asciidoctor-maven-plugin</artifactId>
	<version>2.0.0-RC.1</version>
	<executions>
		<execution>
			<id>output-html</id>
			<phase>generate-resources</phase>
			<goals>
				<goal>process-asciidoc</goal>
			</goals>
			<configuration>
				<backend>html</backend>
			</configuration>
		</execution>
	</executions>
	<dependencies>
		<dependency> <!--1-->
			<groupId>de.uniqueck.asciidoctorj.extensions</groupId>
			<artifactId>asciidoctorj-office-extension</artifactId>
			<version>{version}</version> <!--2-->
		</dependency>
	</dependencies>
</plugin>
----

<1> asciidoctorj-office-extension is added
<2> check for the latest version at https://search.maven.org/search?q=g:de.uniqueck.asciidoctorj.extensions%20AND%20a:asciidoctorj-office-extension[Maven Central]

== Microsoft Powerpoint Extension

=== slide macro

[source]
----
slide::/path/to/powerpointFile.pptx[slideNumber=1]
----

This macro generate an image from the first slide from the given powerpointFile.pptx and embedded it in your asciidoc document.

Currently only Microsofts *.pptx format is supported.


==== Attributes

* **slides-dir-name** output directory name for converted images from slides



== Microsoft Excel Extension

=== excel macro

[source]
----
excel::/path/to/excel.(xlsx|xls)[sheetName=Table1]
----

This macro generate a asciidoc table based on your excel sheet.
Currently supported formats are xls and xlsx.

==== Attributes

* **sheetName** name of sheet to be converted to AsciiDoc table